### PR TITLE
Support net45

### PR DESCRIPTION
**Pull request by viceice**
Hi,

we have a project where we are fixed to build net45 libs. We like to use this lib there.
So i prepared this lib to build against net45.

Regards
Michael

### CODE REVIEW

**Comment by grounded042** [comment]
@ViceIce this looks great. I'm going to bump the version and merge. Thanks for the contribution!

**Comment by viceice** [comment]
Maybe i can send another PR to update changelog and readme. 😄

**Comment by grounded042** [comment]
@ViceIce already done!

**Comment by chrishoffman** [comment]
This no longer is able to be built on a non-Windows platform which is one of the advantages of .NET Core.  I would much prefer seeing how to get this on NET Standard 1.0 to support .NET 4.5.

**Comment by grounded042** [comment]
@chrishoffman that's a good point

**Comment by grounded042** [comment]
I think the only holdout from targeting 1.1 is System.Collections.Specialized.NameValueCollection

**Comment by chrishoffman** [comment]
It doesn't have to use that and there is probably a way to work around it.  I know I've run into library issues trying to go down < 1.3.  I'll probably take a look later.

**Comment by chrishoffman** [comment]
As a side note, I've been meaning to add a travis-ci build configuration to start testing non-Windows building.  I'll add an issue and self assign it.

**Comment by viceice** [comment]
Maybe we should add some condition to add net45 only on windows?

**Pull request merged**
